export type LayoutType = 'single' | 'sidebar' | 'banner' | 'timeline' | 'two-col' | 'traditional';
export type SkillStyle = 'text' | 'pills' | 'dots';

export interface TemplateConfig {
  id: string;
  name: string;
  description: string;
  accentColor: string;
  sidebarBg?: string;
  sidebarText?: string;
  fontFamily: 'serif' | 'sans-serif';
  layout: LayoutType;
  headerAlign: 'left' | 'center';
  dividerStyle: 'line' | 'thick' | 'none' | 'dot' | 'border-left';
  spacing: 'tight' | 'normal' | 'relaxed';
  skillStyle: SkillStyle;
  atsRiskLevel: 'safe' | 'medium' | 'high';
  atsNotes: string;
}

export const TEMPLATES: TemplateConfig[] = [
  // ── SINGLE COLUMN ──────────────────────────────────────────────
  {
    id: 'classic',
    name: 'Classic',
    description: 'Timeless serif, centered header',
    accentColor: '#1e3a5f',
    fontFamily: 'serif',
    layout: 'single',
    headerAlign: 'center',
    dividerStyle: 'line',
    spacing: 'normal',
    skillStyle: 'text',
    atsRiskLevel: 'safe',
    atsNotes: 'Maximum ATS compatibility. Strict top-down reading order.',
  },
  {
    id: 'modern',
    name: 'Modern',
    description: 'Clean sans-serif, indigo accents',
    accentColor: '#4f46e5',
    fontFamily: 'sans-serif',
    layout: 'single',
    headerAlign: 'left',
    dividerStyle: 'line',
    spacing: 'normal',
    skillStyle: 'pills',
    atsRiskLevel: 'safe',
    atsNotes: 'Excellent ATS safety. Simple single-column flow.',
  },
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Whitespace-forward, no dividers',
    accentColor: '#374151',
    fontFamily: 'sans-serif',
    layout: 'single',
    headerAlign: 'left',
    dividerStyle: 'none',
    spacing: 'relaxed',
    skillStyle: 'pills',
    atsRiskLevel: 'safe',
    atsNotes: 'Highly readable by both humans and ATS parsers.',
  },
  {
    id: 'executive',
    name: 'Executive',
    description: 'Bold serif, formal & elegant',
    accentColor: '#111827',
    fontFamily: 'serif',
    layout: 'single',
    headerAlign: 'left',
    dividerStyle: 'thick',
    spacing: 'relaxed',
    skillStyle: 'text',
    atsRiskLevel: 'safe',
    atsNotes: 'Perfect for strict corporate ATS systems like Workday.',
  },
  {
    id: 'sharp',
    name: 'Sharp',
    description: 'Left border accent on sections',
    accentColor: '#0f172a',
    fontFamily: 'sans-serif',
    layout: 'single',
    headerAlign: 'left',
    dividerStyle: 'border-left',
    spacing: 'normal',
    skillStyle: 'pills',
    atsRiskLevel: 'safe',
    atsNotes: 'Left border CSS is ignored by ATS, maintaining safety.',
  },
  {
    id: 'scholar',
    name: 'Scholar',
    description: 'Academic serif, centered formal',
    accentColor: '#4a1942',
    fontFamily: 'serif',
    layout: 'single',
    headerAlign: 'center',
    dividerStyle: 'dot',
    spacing: 'relaxed',
    skillStyle: 'text',
    atsRiskLevel: 'safe',
    atsNotes: 'Academic standard. Very safe parsing.',
  },
  {
    id: 'compact',
    name: 'Compact',
    description: 'Dense layout, max content density',
    accentColor: '#1e40af',
    fontFamily: 'sans-serif',
    layout: 'single',
    headerAlign: 'left',
    dividerStyle: 'line',
    spacing: 'tight',
    skillStyle: 'pills',
    atsRiskLevel: 'safe',
    atsNotes: 'Dense but structurally sound for ATS.',
  },
  {
    id: 'harvard',
    name: 'Harvard',
    description: 'Strict academic standard, zero styling',
    accentColor: '#000000',
    fontFamily: 'serif',
    layout: 'single',
    headerAlign: 'center',
    dividerStyle: 'line',
    spacing: 'tight',
    skillStyle: 'text',
    atsRiskLevel: 'safe',
    atsNotes: 'The gold standard for ATS compatibility. Flawless parsing.',
  },
  {
    id: 'tech-clean',
    name: 'Tech Clean',
    description: 'Silicon Valley standard, highly readable',
    accentColor: '#2563eb',
    fontFamily: 'sans-serif',
    layout: 'single',
    headerAlign: 'left',
    dividerStyle: 'thick',
    spacing: 'normal',
    skillStyle: 'text',
    atsRiskLevel: 'safe',
    atsNotes: 'Standard FAANG-style layout. Exceptionally safe.',
  },
  {
    id: 'startup',
    name: 'Startup',
    description: 'Modern, airy, and impact-focused',
    accentColor: '#10b981',
    fontFamily: 'sans-serif',
    layout: 'single',
    headerAlign: 'left',
    dividerStyle: 'border-left',
    spacing: 'relaxed',
    skillStyle: 'pills',
    atsRiskLevel: 'safe',
    atsNotes: 'Great for modern ATS systems used by startups (Lever, Greenhouse).',
  },

  // ── BANNER HEADER ───────────────────────────────────────────────
  {
    id: 'banner',
    name: 'Banner',
    description: 'Bold full-width colored header',
    accentColor: '#1d4ed8',
    fontFamily: 'sans-serif',
    layout: 'banner',
    headerAlign: 'left',
    dividerStyle: 'none',
    spacing: 'normal',
    skillStyle: 'pills',
    atsRiskLevel: 'medium',
    atsNotes: 'Header color blocks can occasionally confuse very old parsers.',
  },
  {
    id: 'teal-banner',
    name: 'Teal Banner',
    description: 'Teal header band, clean body',
    accentColor: '#0f766e',
    fontFamily: 'sans-serif',
    layout: 'banner',
    headerAlign: 'center',
    dividerStyle: 'line',
    spacing: 'normal',
    skillStyle: 'pills',
    atsRiskLevel: 'medium',
    atsNotes: 'Header structure is safe, but CSS background may hide text from old systems.',
  },

  // ── TIMELINE ───────────────────────────────────────────────────
  {
    id: 'timeline',
    name: 'Timeline',
    description: 'Vertical dot timeline on experience',
    accentColor: '#059669',
    fontFamily: 'sans-serif',
    layout: 'timeline',
    headerAlign: 'left',
    dividerStyle: 'line',
    spacing: 'normal',
    skillStyle: 'pills',
    atsRiskLevel: 'high',
    atsNotes: 'Absolute positioning used for timeline dots breaks left-to-right reading order in many ATS.',
  },

  // ── SIDEBAR dark ───────────────────────────────────────────────
  {
    id: 'atlantic',
    name: 'Atlantic',
    description: 'Navy sidebar + white content area',
    accentColor: '#1e3a5f',
    sidebarBg: '#1e3a5f',
    sidebarText: '#ffffff',
    fontFamily: 'sans-serif',
    layout: 'sidebar',
    headerAlign: 'left',
    dividerStyle: 'line',
    spacing: 'normal',
    skillStyle: 'dots',
    atsRiskLevel: 'high',
    atsNotes: 'Sidebars cause ATS to read across columns (e.g., merging contact info with experience).',
  },
  {
    id: 'slate-sidebar',
    name: 'Slate',
    description: 'Charcoal sidebar, modern profile',
    accentColor: '#4f46e5',
    sidebarBg: '#1e293b',
    sidebarText: '#f1f5f9',
    fontFamily: 'sans-serif',
    layout: 'sidebar',
    headerAlign: 'left',
    dividerStyle: 'none',
    spacing: 'normal',
    skillStyle: 'pills',
    atsRiskLevel: 'high',
    atsNotes: 'High risk of text merging across columns during PDF parsing.',
  },
  {
    id: 'sidebar-light',
    name: 'Sidebar Light',
    description: 'Light gray sidebar, elegant split',
    accentColor: '#4f46e5',
    sidebarBg: '#f1f5f9',
    sidebarText: '#1e293b',
    fontFamily: 'sans-serif',
    layout: 'sidebar',
    headerAlign: 'left',
    dividerStyle: 'line',
    spacing: 'normal',
    skillStyle: 'pills',
    atsRiskLevel: 'high',
    atsNotes: 'Two-column layouts are notoriously poorly parsed by Workday and iCIMS.',
  },

  // ── TWO COLUMN ─────────────────────────────────────────────────
  {
    id: 'two-col',
    name: 'Two Column',
    description: 'Balanced two-column layout',
    accentColor: '#7c3aed',
    fontFamily: 'sans-serif',
    layout: 'two-col',
    headerAlign: 'left',
    dividerStyle: 'line',
    spacing: 'normal',
    skillStyle: 'pills',
    atsRiskLevel: 'high',
    atsNotes: 'Flexbox column structures often fail text extraction tools.',
  },
  {
    id: 'mercury',
    name: 'Mercury',
    description: 'Narrow left panel, wide experience',
    accentColor: '#0369a1',
    fontFamily: 'sans-serif',
    layout: 'two-col',
    headerAlign: 'left',
    dividerStyle: 'none',
    spacing: 'normal',
    skillStyle: 'dots',
    atsRiskLevel: 'high',
    atsNotes: 'Text from the narrow left panel will incorrectly interleave with the main experience content.',
  },

  // ── TRADITIONAL (All-caps name, skills-first, icons) ───────────────────
  {
    id: 'traditional',
    name: 'Traditional',
    description: 'ALL CAPS serif, skills-first, bold categories',
    accentColor: '#000000',
    fontFamily: 'serif',
    layout: 'traditional',
    headerAlign: 'center',
    dividerStyle: 'line',
    spacing: 'normal',
    skillStyle: 'text',
    atsRiskLevel: 'safe',
    atsNotes: 'Classic structural hierarchy. Perfect for all parsers.',
  },
];

export function getTemplate(id: string): TemplateConfig {
  return TEMPLATES.find(t => t.id === id) ?? TEMPLATES[0];
}
